<!-- Recréation de la NavBar pour la page Mentions légales: -->
<?php
    $website = simplexml_load_file(dirname(__FILE__).'/../models/source.xml');
    $home = $website->page[0]->menu;
    $about = $website->page[1]->menu;
    $opinion = $website->page[2]->menu;
    $contact = $website->page[3]->menu;
    include(dirname(__FILE__).'/templates/header.php'); 
?>
<!-- Fin Recréation de la NavBar pour la page Mentions légales: -->

<!-- Mention légales -->
<div class="mx-2">
<h2 class="text-center mb-5">Mentions légales et Conditions d'Utilisation et de Consultation du Présent Site</h2>
<h3 class="text-decoration-underline">1. Présentation du site</h3>
<p class="mb-4">En vertu de l’article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l’économie numérique, il est précisé aux utilisateurs de ce site l’identité des différents intervenants dans le cadre de sa réalisation et de son suivi : Propriétaire : OCORDO, 3 rue maracci Lille Créateur : OCORDO Responsable publication : OCORDO Webmaster : Clément Hébergeur : OVH – 2 RUE KELLERMANN 59100 ROUBAIX</p>
<h3 class="text-decoration-underline">2. Conditions générales d’utilisation du présent site</h3>
<p class="mb-4">L’utilisation de ce site implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs de ce site sont donc invités à les consulter avant chaque visite. Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par OCORDO. Ce site est mis à jour régulièrement. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer avant toute consultation afin d’en prendre connaissance.</p>
<h3 class="text-decoration-underline">3. Description des services fournis dans ce présent site</h3>
<p class="mb-4">Ce site a pour objet de fournir une information succincte et approximative sur un métier ou une activité généralement en lien avec une ou plusieurs entreprises de bâtiment pour lesquelles OCORDO fournie une prestation de services dans l'externalisation commerciale, la prospection commerciale et le suivi commercial de la relation clients. Il est rappelé qu'OCORDO est une société de prestation de services commerciaux pour les entreprises du bâtiment. OCORDO ne réalise elle-même aucune mission de maîtrise d'oeuvre. OCORDO ne réalise pas elle même de travaux de rénovation. Seules les entreprises de bâtiment pour lesquelles OCORDO assure le service commercial réalisent des travaux de rénovation et de construction d'extention. OCORDO s’efforce de fournir sur ce site des informations en lien avec l'activité de ou des entreprises pour lesquelles elle travaille. OCORDO ne pourra être tenue responsable des omissions, des inexactitudes et des carences dans les informations publiées, qu’elles soient de son fait ou du fait d'une entreprise tierse qui lui fournit ces informations. Toutes les informations indiquées sur ce site sont données à titre indicatif, et sont susceptibles d’évoluer. Par ailleurs, les renseignements figurant sur ce site ne sont pas exhaustifs. Ils sont donnés sous toutes réserves et notamment de modifications ayant été apportées depuis leur mise en ligne. Enfin, il se peut que ce site soit en cours de finalisation et d'attente d'affectation à une entreprise pour laquelle OCORDO travaille. Le numéro de téléphone, le courriel et le formulaire contact figurant sur ce site sont ceux du standard d'OCORDO qui centralise les appels et mails pour le compte d'entreprises pour lesquelles elle travaille. Lors d'une demande de renseignements ou de devis par mail ou téléphone il vous sera demandé de préciser la source sur laquelle vous avez trouvé les coordonnées. Il vous appartient alors d'indiquer précisément le nom de domaine, l'adresse web ou l'url de ce site afin que votre demande puisse être précisément transmise si vous le souhaitez.</p>
<h3 class="text-decoration-underline">4. Limitations de responsabilité technique</h3>
<p class="mb-4">Le site utilise la technologie JavaScript. Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour.</p>
<h3 class="text-decoration-underline">5. Propriété intellectuelle et contrefaçons</h3>
<p class="mb-4">OCORDO est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels. Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de OCORDO. Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément notamment aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
<h3 class="text-decoration-underline">6. Limitations de responsabilité</h3>
<p class="mb-4">OCORDO ne pourra être tenue responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès à ce site, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité. OCORDO ne pourra également être tenue responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation de ce site. Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. OCORDO se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant, OCORDO se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie…).</p>
<h3 class="text-decoration-underline">7. Gestion des données personnelles</h3>
<p class="mb-4">En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l’article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995. A l’occasion de l’utilisation du présent site, peuvent êtres recueillies : l’URL des liens par l’intermédiaire desquels l’utilisateur a accédé au présent site, le fournisseur d’accès de l’utilisateur, l’adresse de protocole Internet (IP) de l’utilisateur et toutes autres informations informatiquement collectables. En tout état de cause OCORDO collecte des informations personnelles relatives à l’utilisateur pour le besoin de certains services proposés par le présent site et pour les besoins de son activité. L’utilisateur fournit ces informations en toute connaissance de cause, et en particulier lorsqu’il procède par lui-même à leurs saisies. Le cas échéant, il peut être précisé à l’utilisateur du présent site l’obligation ou non de fournir ces informations. Toutes informations fournies par l'utilisateurs pourront être transmises aux entreprises pour lesquelles OCORDO travaille ou aux entreprises partenaires d'OCORDO a des fins notamment de démarchage commercial ou d'action marketing. Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée à l'adresse mentionné au 1., accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée. Certaines informations à caractère personnel de l’utilisateur du présent site pourront être publiées, échangées, transférées, cédées ou vendues sur un support quelconque à des tiers.</p>
<h3 class="text-decoration-underline">8. Liens hypertextes et cookies</h3>
<p class="mb-4">Le présent site contient un certain nombre de liens hypertextes vers d’autres sites. Cependant, OCORDO n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait. La navigation sur le présent site est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas forcément l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation. Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. L’utilisateur peut toutefois configurer son ordinateur de la manière suivante, pour refuser l’installation des cookies : Sous Internet Explorer : onglet outil (pictogramme en forme de rouage en haut a droite) / options internet. Cliquez sur Confidentialité et choisissez Bloquer tous les cookies. Validez sur Ok. Sous Firefox : en haut de la fenêtre du navigateur, cliquez sur le bouton Firefox, puis aller dans l’onglet Options. Cliquer sur l’onglet Vie privée. Paramétrez les Règles de conservation sur : utiliser les paramètres personnalisés pour l’historique. Enfin décochez-la pour désactiver les cookies. Sous Safari : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par un rouage). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section « Confidentialité », cliquez sur Paramètres de contenu. Dans la section « Cookies », vous pouvez bloquer les cookies. Sous Chrome : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par trois lignes horizontales). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section « Confidentialité », cliquez sur préférences. Dans l’onglet « Confidentialité », vous pouvez bloquer les cookies.</p>
<h3 class="text-decoration-underline">9. Droit applicable et attribution de juridiction</h3>
<p class="mb-4">Tout litige en relation avec l’utilisation du présent site est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Lille.</p>
</div>
<!-- Fin Mentions légales -->

<!-- Footer -->
<?php include(dirname(__FILE__).'/templates/footer.php'); ?>
